name: "document-suite"

networks:
  document-network:
    driver: bridge

# volumes:
# minio_data: null
# rustfs_data: null
# rustfs_logs: null
# pg_data: null
# temporal_data: null
# qdrant_data: null

services:
  mlflow:
    # TODO - use a dedicated postgres database instead of maindb
    image: ghcr.io/mlflow/mlflow:${MLFLOW_VERSION}
    networks: [document-network]
    container_name: mlflow
    # volumes:
    #   - # TODO
    depends_on:
      postgres:
        condition: service_healthy
      rustfs:
        condition: service_healthy
      rustfs-create-bucket:
        condition: service_completed_successfully
    environment:
      MLFLOW_BACKEND_STORE_URI: ${MLFLOW_BACKEND_STORE_URI}
      MLFLOW_S3_ENDPOINT_URL: ${S3_ENDPOINT_URL}
      MLFLOW_ARTIFACTS_DESTINATION: ${MLFLOW_ARTIFACTS_DESTINATION}

      AWS_ACCESS_KEY_ID: ${RUSTFS_ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${RUSTFS_SECRET_KEY}
      AWS_DEFAULT_REGION: ${AWS_REGION}
      MLFLOW_S3_IGNORE_TLS: "true" # TODO

      MLFLOW_HOST: ${MLFLOW_HOST}
      MLFLOW_PORT: ${MLFLOW_PORT}
    ports:
      - "${MLFLOW_PORT}:${MLFLOW_PORT}"
    command:
      - /bin/bash
      - -c
      - |
        pip install --no-cache-dir psycopg2-binary boto3
        mlflow server \
          --backend-store-uri ${MLFLOW_BACKEND_STORE_URI} \
          --artifacts-destination ${MLFLOW_ARTIFACTS_DESTINATION} \
          --serve-artifacts \
          --host ${MLFLOW_HOST} \
          --port ${MLFLOW_PORT}

