name: "workflow-system"

services:
  temporal:
    image: temporalio/auto-setup:${TEMPORAL_VERSION}
    container_name: ${TEMPORAL_CONTAINER_NAME}
    networks: [document-network]
    # volumes:
    #   - temporal_data:/etc/temporal/config/dynamicconfig
    depends_on:
      - ${POSTGRES_CONTAINER_NAME}
    environment:
      DB: postgres12
      DB_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PWD: ${POSTGRES_PASSWORD}
      POSTGRES_SEEDS: postgres # TODO : find out what this means
      # DYNAMIC_CONFIG_FILE_PATH: config/dynamicconfig/development-sql.yaml
      TEMPORAL_ADDRESS: ${TEMPORAL_CONTAINER_NAME}:7233
      TEMPORAL_CLI_ADDRESS: ${TEMPORAL_CONTAINER_NAME}:7233
  # temporal-admin-tools:
  #   image: temporalio/admin-tools:${TEMPORAL_ADMINTOOLS_VERSION}
  #   container_name: temporal-admin-tools
  #   depends_on:
  #     - temporal
  #   environment:
  #     - TEMPORAL_ADDRESS=temporal:${TEMPORAL_PORT}
  #     - TEMPORAL_CLI_ADDRESS=temporal:${TEMPORAL_PORT}
  #   stdin_open: true
  #   tty: true
  temporal-ui:
    image: temporalio/ui:${TEMPORAL_UI_VERSION}
    container_name: temporal-ui
    networks: [document-network]
    depends_on:
      - temporal
    environment:
      TEMPORAL_ADDRESS: ${TEMPORAL_CONTAINER_NAME}:7233
      # TEMPORAL_CORS_ORIGINS: http://localhost:3000
    ports:
      - "${TEMPORAL_UI_PORT}:8080"
  workflows:
    build:
      context: ./workflow
    container_name: workflow
    networks: [document-network]
    depends_on:
      - temporal
    environment:
      WORKFLOW_BIND: ${WORKFLOW_ADDRESS}:${WORKFLOW_PORT}

      TEMPORAL_ADDRESS: ${TEMPORAL_CONTAINER_NAME}:7233
      TEMPORAL_NAMESPACE: default
      
      POSTGRES_ADDRESS: ${POSTGRES_CONTAINER_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB} # TODO - change to its own databse based on migration {POSTGRES_WORKFLOW_DB}
      
      AWS_REGION: ${AWS_REGION}
      S3_ENDPOINT_URL: ${S3_ENDPOINT_URL}
      RUSTFS_ACCESS_KEY: ${RUSTFS_ACCESS_KEY}
      RUSTFS_SECRET_KEY: ${RUSTFS_SECRET_KEY}

      DOCUMENT_S3_BUCKET: ${DOCUMENT_S3_BUCKET}
    ports:
      - "${WORKFLOW_PORT}:${WORKFLOW_PORT}"
    healthcheck:
      test:
        [
          "CMD",
          "/bin/sh",
          "-c",
          "wget -qO- http://localhost:${WORKFLOW_PORT}/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

