// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package datamodel

import (
	"time"

	"github.com/samborkent/uuidv7"
)

type HubDocument struct {
	Uuid uuidv7.UUID
	Ldts time.Time
	Udts time.Time
}

type HubDocumentPage struct {
	Uuid              uuidv7.UUID
	Ldts              time.Time
	Udts              time.Time
	Documentpageindex int16
}

type HubTextChunk struct {
	Uuid    uuidv7.UUID
	Ldts    time.Time
	Udts    time.Time
	Content string
}

type HubVectorization struct {
	Uuid uuidv7.UUID
	Ldts time.Time
	Udts time.Time
}

type LnkDocumentDocumentPage struct {
	Documentuuid     uuidv7.UUID
	Documentpageuuid uuidv7.UUID
	Ldts             time.Time
}

type LnkDocumentTextChunk struct {
	Documentuuid  uuidv7.UUID
	Textchunkuuid uuidv7.UUID
	Ldts          time.Time
}

type LnkTextChunkVectorization struct {
	Textchunkuuid     uuidv7.UUID
	Vectorizationuuid uuidv7.UUID
	Ldts              time.Time
}

type SatDocumentMetadata struct {
	Documentuuid uuidv7.UUID
	Ldts         time.Time
	Udts         time.Time
	Documenthash string
	Name         string
}
