// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package datamodel

import (
	"context"

	"github.com/samborkent/uuidv7"
)

const getAllDocuments = `-- name: GetAllDocuments :many
SELECT uuid, ldts, udts FROM Hub_Document
`

func (q *Queries) GetAllDocuments(ctx context.Context) ([]HubDocument, error) {
	rows, err := q.db.QueryContext(ctx, getAllDocuments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HubDocument{}
	for rows.Next() {
		var i HubDocument
		if err := rows.Scan(&i.Uuid, &i.Ldts, &i.Udts); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllPagesForDocument = `-- name: GetAllPagesForDocument :many
SELECT Hub_Document_Page.UUID
FROM Hub_Document
JOIN Lnk_Document_Document_Page AS link ON Hub_Document.UUID = Lnk_Document_Document_Page.DocumentUUID
JOIN Hub_Document_Page ON link.DocumentPageUUID = Hub_Document_Page.UUID
WHERE Hub_Document.UUID = $1
`

func (q *Queries) GetAllPagesForDocument(ctx context.Context, uuid uuidv7.UUID) ([]uuidv7.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getAllPagesForDocument, uuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuidv7.UUID{}
	for rows.Next() {
		var uuid uuidv7.UUID
		if err := rows.Scan(&uuid); err != nil {
			return nil, err
		}
		items = append(items, uuid)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
